name = "ParametricOptInterface"
uuid = "0ce4ce61-57bf-432b-a095-efac525d185e"
authors = ["Tom√°s Gutierrez <tomasfmgutierrez@gmail.com>"]
version = "0.14.3"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
MathOptInterface = "1.13.2"
julia = "1.6"
